
# redis 主从哨兵配置
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8
      min-idle: 0
    timeout: 0
    # 主节点哨兵名
    sentinel:
      master: mymaster
      # comma-separated list of host:port pairs  哨兵节点配置列表
      nodes: 127.0.0.1:26380,127.0.0.1:26381
