

## 2.x默认连接池

spring:
  redis:
    cluster:
      nodes:
        - 127.0.1.1:7001
        - 127.0.1.1:7002
        - 127.0.1.1:7003
        - 127.0.1.1:7004
        - 127.0.1.1:7005
        - 127.0.1.1:7006
      max-redirects: 3  # 获取失败 最大重定向次数
    pool:
      max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
      max-idle: 10    # 连接池中的最大空闲连接
      max-wait: -1   # 连接池最大阻塞等待时间（使用负值表示没有限制）
      min-idle:  5     # 连接池中的最小空闲连接
    timeout: 6000  # 连接超时时长（毫秒）

# 使用jedis连接池
#
#spring:
#  redis:
#    password:    # 密码（默认为空）
#    timeout: 6000ms  # 连接超时时长（毫秒）
#    cluster:
#      nodes:
#        - 127.0.1.1:7001
#        - 127.0.1.1:7002
#        - 127.0.1.1:7003
#        - 127.0.1.1:7004
#        - 127.0.1.1:7005
#        - 127.0.1.1:7006
#    jedis:
#      pool:
#        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
#        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-idle: 10      # 连接池中的最大空闲连接
#        min-idle: 5       # 连接池中的最小空闲连接


